### ISSUE TITLE
Should the MultiAddress  be fixed?

### ISSUE THREAD

**Issue by wanderer** [libp2p/interface-transport#3]
Currently the [MultiAddress](https://github.com/diasdavid/interface-transport/blob/master/tests/base-test.js#L9) is always tcp. How would this test facilitate other transports? Maybe have a method to generate a multiAddress?

**Comment by diasdavid** [comment]
agree, it should be one more option passed to the constructor, the only requirement should it to be a multiaddr

**Comment by jacobheun** [comment]
No longer an issue, tests are bootstrapped with addresses.
