### ISSUE TITLE
start and stop accepting connections

### ISSUE THREAD

**Issue by pgte** [libp2p/interface-transport#34]
To allow denying new connections before they're established, the transport interface must expose a way to stop accepting new connections, as well as start accepting them again.

[First discussed here](https://github.com/libp2p/js-libp2p-connection-manager/issues/2).

The proposed API here is adding two methods `.start()` and `.stop()`.
For backwards compatibility, by default, the transport starts in the "accepts connections" state.

**Comment by diasdavid** [comment]
I feel this belongs to `libp2p-switch`. A Transport will always yield the connection to the switch which then handles it to SECIO. Before that happens, the connection can be terminated.

**Comment by pgte** [comment]
@diasdavid yes, but wouldn't stopping a listener, (at least in some transports), also destroy all the underlying connections?

**Comment by diasdavid** [comment]
It doesn't destroy (or shouldn't) it actually waits for them to close and rejects new ones meanwhile.

**Comment by pgte** [comment]
Here, in the websocket-star protocol, it definitely closes the connection to the relay/discovery server: https://github.com/libp2p/js-libp2p-websocket-star/blob/master/src/listener.js#L77-L85

**Comment by pgte** [comment]
Which would, AFAIK, terminate all the underlying relayed connections..

**Comment by diasdavid** [comment]
@pgte that's a bug then :)

**Comment by pgte** [comment]
OK, filed issue here: https://github.com/libp2p/js-libp2p-websocket-star/issues/49

**Comment by pgte** [comment]
Also a bug in libp2p-tcp: https://github.com/libp2p/js-libp2p-tcp/issues/92

**Comment by pgte** [comment]
Tracking here: https://github.com/libp2p/js-libp2p-switch/issues/251
