### ISSUE TITLE
docs: listener.stop() says it destroys all connections

### ISSUE THREAD

**Issue by pgte** [libp2p/interface-transport#35]
> options is an optional object that might contain the following properties:
> * timeout - A timeout value (in ms) that fires and destroys all the connections on this transport if the transport is not able to close graciously. (e.g { timeout: 1000 })

Closing a listener doesn't mean we have to destroy all connections. (In fact, the webrtc-star transport doesn't do this). It only should mean that we don't want to accept new connections any longer.

**Comment by jacobheun** [comment]
Closing this out as the desired behavior and new methods are covered in https://github.com/libp2p/interface-transport/issues/39
